### ISSUE TITLE
Sampling options values 

### ISSUE THREAD

**Issue by FAMILIAR-project** [diverse-project/varylatex#2]
There are several ways to pick some values and set a configuration. 
I propose to implement a naive algorithm that will *randomly* pick a value of an option... and does that for all options.

In case it's Boolean, 50% true/false... 
In case it's numerical, randomly over the possible values (for double/float we need to have a kind of precision see eg https://stackoverflow.com/a/31595824/13748216) 

I have impression we need to explicitly specify the "type" of option somewhere

**Comment by c-a-m-o** [comment]
Mostly added in commit 8f44cd87e75093808800ea3a1c081601740b73e4
Numerical and boolean values are supported, as well as variables that can have a finite amount of values.

The problem with this method is that there are no more  relationships between variables, leading to different configs having the same outcome which may not be optimal.
