### ISSUE TITLE
Sampling, observing, and storing results in a CSV

### ISSUE THREAD

**Issue by FAMILIAR-project** [diverse-project/varylatex#3]
The process is as follows:
 * sample a subset of configuration (see issue #2)... we can fix the "budget", like N=100 configurations
 * compute some information about each configuration (eg number of pages, see issue #1) 
 * store everything in a CSV file... headers would be the options and the computed information 

example is given here: https://github.com/FAMILIAR-project/varylatex/blob/master/output-FSE/stats.csv

**Comment by c-a-m-o** [comment]
Done in d80d0c74b415a8dd802f317cb2829e3501380fbd using the `pandas` python library.
For now, it stores the values of the variables, the amount of pages and the size of the largest empty block in the last page of the document.
