### ISSUE TITLE
decision tree out of CSV file

### ISSUE THREAD

**Issue by FAMILIAR-project** [diverse-project/varylatex#6]
in order to validate the CSV and to make it more concrete (issue #3), it's interesting to test whether we can apply a learning algorithm... in the mid-term, we will implement it in Python and scikit-learn

but a quick test can be to adapt this R script:
https://github.com/FAMILIAR-project/varylatex/blob/master/output-FSE/analysisCT.R
(you have to change at least line 6: https://github.com/FAMILIAR-project/varylatex/blob/master/output-FSE/analysisCT.R#L6 but certainly other columns) 
and see if it works
it was working well with Rstudio 

another quick test can be to adapt this code: 
https://github.com/VaryVary/ML-configurable-SPLCTutorial/blob/master/latex/Latex_specialization.ipynb

 - [x] push some CSV example
 - [x] make the R script work 
 - [ ] make the scikit-learn notebook work (https://github.com/VaryVary/ML-configurable-SPLCTutorial/blob/master/latex/Latex_specialization.ipynb) 
 - [x] integrate the scikit-learn implementation as part of the toolchain

**Comment by c-a-m-o** [comment]
An example of a [300 entries CSV document](https://github.com/diverse-project/varylatex/blob/140ce2bf8a37b069f71e692e1265ac5d9dcb5eed/result_example.csv) has been added in commit a1a758807f261b51bf69cae59714f0e3d6c70501 and [another one of 3000 entries](https://github.com/diverse-project/varylatex/blob/140ce2bf8a37b069f71e692e1265ac5d9dcb5eed/result_long_example.csv) in commit c457ac06c58ee572f10847b07c96e7b6a995e8a4.
The R script is working and uses the 300-entries example.
The python script can be used alone using the larger example or can be imported, which is done at the end of the main script
