### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by FAMILIAR-project** [diverse-project/varylatex#8]
specify a Dockerfile to build a Docker image https://docs.docker.com/get-started/ containing all tools/library needed (and automated the installation...) 
we can use an Ubuntu-like image

as a nice bonus it should be "easy" to call varylatex out of the Docker image 
something like

`docker run -v $(pwd):/varylatex diverse/varylatex` 
where pwd is the location of the LaTeX folder 

or #7 
`docker run diverse/varylatex https://overleafrepo`

**Comment by c-a-m-o** [comment]
There is now a [Dockerfile](https://github.com/diverse-project/varylatex/blob/5120a4f7ed2ef7a088be451d56af8feb4fd3c032/Dockerfile) that allows to build an image with the necessary libraries.
Please note that the created image is quite heavy as it installs the `texlive-full` package for completeness. The total size is almost 7GB.

To build it : `docker build -t varylatex .` in the directory
Example run command :
```bash
sudo docker run --rm\
  -v $(pwd)/<rel_path_to_sources_folder>:/varylatex/source \
  -v $(pwd)/<rel_path_to_output_folder>:/varylatex/output varylatex \
  python optimizer.py <main .tex file name>
```
